gifts:
  first:
    name: "&dЖопа"
    hash: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjhkYzNjODQ0OTFjNGZmMTAzZGU2ZWEwMTg4MGUyZDgzNDMyY2Q0ODc4Yjg0ZDZiNDMyNTNjYzUxZmQ5NzhlNyJ9fX0="
    sound: ENTITY_PLAYER_LEVELUP
    commands:
      - "give %player% apple 1"
      - "eco give %player% 500"
  second:
    name: "&dНеЖопа"
    hash: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWJkOTg3OTJkZDkyZDk3MTk4OTQzNDFhYzkwMTJhNTg0YzQ0Mjg1NThmZDJjNzEyZjc4ZTVmMGQ0ZGE4NTQ3MCJ9fX0="
    sound: ENTITY_PLAYER_LEVELUP
    commands:
      - "give %player% apple 2"
      - "eco give %player% 500"


messages:
  no-perms: "&cНет прав!"
  reloaded: "&aПлагин успешно перезагружен!"
  taken: "&dВы нашли подарок %gift%"
  no-space: "&cВ вашем инвентаре не хватает места!"
  gift-given: "&aПодарок выдан, поставьте его!"
  gift-not-exists: "&cПодарок с таким названием не существует!"
  already-taken: "&cВы уже нашли этот подарок!"
  no-args: "&cНе хватает аргументов"
